// Styles
import "@/styles/globals.css";

// Libs
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

// Clerk
import { UserButton, auth, currentUser } from "@clerk/nextjs";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from '@clerk/themes';

// Providers
import { SocketProvider } from "@/context/SocketProvider";
import { ThemeProvider } from "@/context/ThemeProvider";
import { TRPCReactProvider } from "@/trpc/react";

// Components
import { Toaster } from "@/components/ui/sonner";
import { Button } from "@/components/ui/button";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { ModeToggle } from "@/components/ThemeToggle";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { userId } = auth();
  const user = await currentUser();

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <TRPCReactProvider>
        <ClerkProvider
          appearance={{
            baseTheme: dark,
          }}
        >
          <SocketProvider>
            <body className={inter.className} suppressHydrationWarning={true}>
              <ThemeProvider attribute="class" defaultTheme="system">
                <main>
                  <nav className="fixed flex w-screen items-center justify-between px-4 py-2">
                    <span>Watch-Together</span>
                    <div className="flex items-center justify-between gap-2">
                      <ModeToggle />
                      {user ? (
                        <UserButton afterSignOutUrl="/" />
                      ) : (
                        <div className="flex gap-2">
                          <Link href={"/sign-in"}>
                            <Button variant={"outline"}>Sign In</Button>
                          </Link>
                          <Link href={"/sign-up"}>
                            <Button>Sign Up</Button>
                          </Link>
                        </div>
                      )}
                    </div>
                  </nav>
                  {children}
                </main>
                <Toaster />
              </ThemeProvider>
            </body>
          </SocketProvider>
        </ClerkProvider>
      </TRPCReactProvider>
    </html>
  );
}
